FROM python:3.11.2

RUN pip install schedule mysql-connector-python python-openstackclient

RUN mkdir /scheduler
WORKDIR /scheduler

ENV DB_HOST="127.0.0.1"
ENV DB_NAME="vdi4"
ENV DB_USER="root"
ENV DB_PASSWORD="azerty"

ENV OPENSTACK_PRIVATE_NETWORK_ID="0d49c37b-7077-4152-985c-f5a00ad20677"
ENV OPENSTACK_USERNAME="admin"
ENV OPENSTACK_PASSWORD="3pMrmW899b9y^2kiJa!6#Z#kE%@a2r"
ENV OPENSTACK_AUTH_URL = "http://172.10.3.60:5000/v3"
ENV OPENSTACK_PROJECT_NAME = "admin"
ENV OPENSTACK_USER_DOMAIN_ID = "default"
ENV OPENSTACK_PROJECT_DOMAIN_ID = "default"

COPY scheduler.py .
COPY back_openstack.py .

CMD ["python", "scheduler.py"]